### ISSUE TITLE
[Sticky] Sprint Goals 🏑

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1162]
Overall priorities

1. Code documentation and cleanup
2. Tests
3. Code changes
3.1 reviews
3.2 in progress
3.3 backlog

In progress
* [ ] investigate 2.5 to 2.6 update #1115 
* [x] target customization is first applied then lost #1079 

Backlog
* [x] Empty bundle created #737
