### ISSUE TITLE
Epic: Public API

### ISSUE THREAD

**Issue by manno** [rancher/fleet#1736]
- [x] https://github.com/rancher/fleet/issues/1555
- [ ] https://github.com/rancher/fleet/issues/1631 - not needed?
- [x] https://github.com/rancher/fleet/issues/1495 - move to controller-gen
- [x] kubectl describe show docs
